$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: hello_pipeline_abc
compute: azureml:githubcluster
  
inputs:
  kernel_top_level_input: "linear"
  penalty_top_level_input: 1.0
jobs:
  a:
    code: train
    command: >-
      python train.py
      --kernel ${{inputs.kernel}}
      --penalty ${{inputs.penalty}}
    inputs:
      kernel: ${{parent.inputs.kernel_top_level_input}}
      penalty: ${{parent.inputs.penalty_top_level_input}}
    environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
    description: This pipeline job is created from cli  


